# Generated by Django 5.2.6 on 2025-11-02 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_pedido_pedidoitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca'], name='tienda_prod_marca_401cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='tienda_prod_stock_f652c4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['active', 'stock'], name='tienda_prod_active_bf097b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['seller', 'active'], name='tienda_prod_seller__ac4483_idx'),
        ),
    ]
