# Generated by Django 5.2.6 on 2025-11-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_producto_tienda_prod_marca_401cb4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
