# Generated by Django 5.2.6 on 2025-11-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.URLField(blank=True, help_text='URL de la imagen del producto', null=True),
        ),
    ]
