# Generated by Django 5.2.6 on 2025-11-02 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0008_producto_tienda_prod_marca_401cb4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TendenciaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('productos_trending', models.JSONField(default=list)),
                ('demanda_score', models.FloatField(default=0.0)),
                ('precio_tendencia', models.CharField(choices=[('subiendo', 'Precios Subiendo'), ('bajando', 'Precios Bajando'), ('estable', 'Precios Estables')], default='estable', max_length=20)),
                ('fecha_analisis', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('productos_sugeridos', models.JSONField(default=list)),
                ('productos_abandonados', models.JSONField(default=list)),
                ('score_intencion_compra', models.FloatField(default=0.0)),
                ('ultimo_recordatorio', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComparacionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_promedio_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_oferta', models.BooleanField(default=False)),
                ('porcentaje_ahorro', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_confianza', models.FloatField()),
                ('razon', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_origen', to='tienda.producto')),
                ('producto_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_destino', to='tienda.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'producto_origen', 'producto_recomendado')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioComportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('view', 'Vio el producto'), ('cart', 'Agregó al carrito'), ('buy', 'Compró el producto'), ('search', 'Buscó producto similar'), ('compare', 'Comparó precios')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tiempo_en_pagina', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_5d61ab_idx'), models.Index(fields=['producto', 'accion'], name='analytics_u_product_23b158_idx')],
            },
        ),
    ]
