# Generated by Django 5.2.6 on 2025-10-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_profile_avatar_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat de Telegram para notificaciones', max_length=50, null=True, unique=True),
        ),
    ]
